### ISSUE TITLE
the function faSomeRecords was not found

### ISSUE THREAD

**Issue by lakhujanivijay** [sethiyap/fastaR#1]
Hi @sethiyap 

Someone is seeking help on [biostars](https://www.biostars.org/p/435344/#435364)

**Comment by sethiyap** [comment]
Hi @lakhujanivijay,

Thank you for notifying me about the issue. I have updated the package and documentation.

**Comment by sethiyap** [comment]
Hi @lakhujanivijay 

Thank you for notifying me about the issue. I have updated the package and documentation.
